#!/usr/bin/env python

import requests
import sys

def isnumber(x):
	try:
		n = float(x)
		return True
	except:
		return False

n = 0
fxfrom = ''
fx = ''
for a in sys.argv[1:]:
	if isnumber(a):
		n = float(a)
	elif fxfrom == '':
		fxfrom = a.upper()
	else:
		fx = a.upper()

if fx == '':
	fx = 'HUF'

print(fxfrom, '->', fx, n)

url = 'https://api.exchangeratesapi.io/latest?base=' + fxfrom + '&symbols=' + fx
json = requests.get(url).json()

rate = json['rates'][fx]

print(str(n) + fxfrom + ' = \033[1m' + str(int(float(rate) * n)) + '\033[0m' + str(fx))


	
