#!/usr/bin/env python

import requests
import sys
import platform

CURSES_PRE = '' if 'Windows' in platform.system() else '\033[1m'
CURSES_POST = '' if 'Windows' in platform.system() else '\033[0m'

def isnumber(x):
	try:
		n = float(x)
		return True
	except:
		return False

n = 0
fxfrom = ''
fx = ''
for a in sys.argv[1:]:
	if isnumber(a):
		n = float(a)
	elif fxfrom == '':
		fxfrom = a.upper()
	else:
		fx = a.upper()


print(fxfrom, '->', fx, n)

if fxfrom == '' and fx == '':
	url = 'https://api.exchangeratesapi.io/latest?base=HUF'
	json = requests.get(url).json()

	for fx in ['EUR', 'USD', 'GBP']:
		rate = json['rates'][fx]
		print(str(n) + fx  + ' = ' + CURSES_PRE + str(int(float(n) / float(rate))) + CURSES_POST + 'HUF')
else:
	if fx == '':
	        fx = 'HUF'
	url = 'https://api.exchangeratesapi.io/latest?base=' + fxfrom + '&symbols=' + fx
	json = requests.get(url).json()
	print(url)
	print(json)
	rate = json['rates'][fx]
	print(str(n) + fxfrom + ' = ' + CURSES_PRE + str(int(float(rate) * n)) + CURSES_POST + str(fx))

